### ISSUE TITLE
Autoplay, Default URL, and Default Playlist Support

### ISSUE THREAD

**Issue by ShiguriVR** [synergiance/SynMediaPlayer#13]
I feel like support for a default list of videos that playback on-load is a pretty standard feature.
Merlin's already has this feature where it has a default URL field and you can add more by pressing a "+" button.
This is intended to be used alongside autoplay of course, so that should be added as well.

Just feel like these are pretty standard across video players and should definitely exist.

**Comment by synergiance** [comment]
This should probably be broken up into 3 separate issues.  I'll leave it open as an umbrella issue though.

**Comment by synergiance** [comment]
Default URLs and Default Playlists are available in the experimental branch.  This issue will be closed automatically.
