### ISSUE TITLE
[Suggestion] Make use of on-demand render textures

### ISSUE THREAD

**Issue by ShiguriVR** [synergiance/SynMediaPlayer#46]
Render texture constructors are now exposed to Udon.
This could be taken advantage of for better performance and flexibility.

Could also be relevant for you to add an in-game video quality option?

**Comment by synergiance** [comment]
This won't be fully solved for now but this'll have to do. No longer are the predefined render textures a thing other than the final render texture. It appears that custom render textures cannot be created even though render textures can. https://github.com/synergiance/SynMediaPlayer/commit/7ace9c008d45299fc6559a25628274321312ac0c
