### ISSUE TITLE
[Suggestion] Hardening Against Modified Clients

### ISSUE THREAD

**Issue by ShiguriVR** [synergiance/SynMediaPlayer#48]
In some cases users using modified clients can bypass the media player's authorization settings.
This is because, in most players, authorization is just a matter of UI lockout, which clients can bypass.
It would be nice if the player could be hardened against this problem. Important for popular worlds.

**Comment by synergiance** [comment]
I've got some hardening, which I probably will improve in the future. Data validation succeeds reliably, with a bit of a noisy situation if validation fails.
