### ISSUE TITLE
Diagnostic dump for debugging

### ISSUE THREAD

**Issue by PhaxeNor** [synergiance/SynMediaPlayer#5]
A few options;

- Dump current debug info with debug.log
- Store debug info every N seconds, then dump all once it reaches the end.

**Comment by synergiance** [comment]
I've got some methods set up here, just need to implement the UI methods to point to it.

**Comment by synergiance** [comment]
@PhaxeNor says put the button in the info area, which means, waiting on issue #2 here

**Comment by synergiance** [comment]
Diagnostics implemented and pushed to Testing branch
